# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :magicpod_create_app do
    app_dir_path = "/Users/rei/magicpod_created_app"

    build_ios_app(
        scheme: "magic_pod_demo_app",
        project: "magic_pod_demo_app.xcodeproj",
        configuration: "Debug",
        export_method: "ad-hoc",
        derived_data_path: app_dir_path,
        skip_package_ipa: true,
        skip_archive: true,
        destination: "generic/platform=iOS Simulator"
    )

    # add actions here: https://docs.fastlane.tools/actions
  end
end