# Git Pushした時にこのワークフローを実行する
on: [push]

jobs:
  # job名(任意の名前)
  magic_pod_job:
    # virtual machineの形式を指定 
    runs-on: macos-latest
    name: Run batch test
    # jobのステップ
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # actionsのバージョン。最新をセットしてください
      - name: set up ruby # Rubyをインストール
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: bundle install # Gem系ライブラリインストール
        run: bundle install
      - name: bundle update 
        run: bundle update
      - name: setup brew # brewをインストール
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Select Xcode version # Xcode 13.2.1 を使う
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
      - name: Show Xcode version
        run: xcodebuild -version
     # ステップ1(アプリを作成する)
        # ステップ名1
      - name: Create app
        run: bundle exec fastlane magicpod_create_app #Fastfileで指定したレーン名
     # ステップ2(作成したアプリをMagicPodにアップロードし一括実行する)
        # ステップ名2
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGIC_POD_API_TOKEN }} #GitHubで設定した変数名
        run: bash run_magicpod_test.sh

