# Pushした時にこのワークフローを実行する
on: [push]

jobs:
  # job名(任意のjob名)
  magic_pod_job:

    # virtual machineの形式を指定
    runs-on: macos-latest  #今回はmacを指定

    # job内のステップ
    steps:
      # ステップ1(チェックアウト)
      - name: Checkout
        uses: actions/checkout@v3 # actionsのバージョンは最新を指定
    # ステップ2(Rubyをインストール)
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
    # ステップ3(Fastlaneインストール)
      - name: Install Fastlane
        run: gem install fastlane
    # ステップ4(brewをインストール)
      - name: Setup brew
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
    # ステップ5(Xcode 13.2.1 を選択)
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
    # ステップ6(Xcodeのバージョンを出力)
      - name: Show Xcode version
        run: xcodebuild -version
    # ステップ7(アプリを作成する)
      - name: Create app
        run: fastlane magicpod_create_app  #Fastfileで指定したlane名
    # ステップ8(作成したアプリをMagicPodにアップロードし一括実行する)
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGIC_POD_API_TOKEN }}  #GitHubで設定した変数名
        run: bash run_magicpod_test.sh  #先ほど作成したシェルスクリプト
